// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//  find the sum of the even-valued terms.

const euler002 = ()=>{
    let firstnum = 0,secondnum=1,thirdnum=0,sum=0;
    for(let i=0;i<40;i++){
        thirdnum=firstnum+secondnum;
        firstnum = secondnum;
        secondnum = thirdnum;
        if(thirdnum%2==0)
        sum+=thirdnum;
        if(sum>4000000)
        break;
    }
    console.log(sum);
}
euler002();